### ISSUE TITLE
Can we make launch materials open?

### ISSUE THREAD

**Issue by maryamanuelnhsx** [nhs-pycom/nhs.pycom#11]
Hi @craig-shenton (cc: @Arouba), the launch materials on the event page keeps blocking users - saying "you can't access this webpage" even though they should be able to access it 

![image](https://user-images.githubusercontent.com/73167040/121863516-d950c300-ccf3-11eb-817e-dc789e071140.png)

![image](https://user-images.githubusercontent.com/73167040/121863981-4ebc9380-ccf4-11eb-8975-46c4676918e6.png)

Is there a way we can embed the slides on our webpage, so we can keep it open, without having to ask users to sign up to anything?

**Comment by craig-shenton** [comment]
@maryamanuelnhsx @Arouba updated to link to the slides saved on github: [https://nhs-pycom.net/events.html](https://nhs-pycom.net/events.html). [[commit link](https://github.com/nhs-pycom/nhs.pycom/commit/36f1f94d08a819a7d45f8fb9461a2be5e60afb48)]

**Comment by maryamanuelnhsx** [comment]
Looks fab, thank you for updating @craig-shenton!
